### **Undergraduate Thesis**  

**SURVIVAL ANALYSIS IN A STUDY OF THE DOUBLE BURDEN OF MALNUTRITION**  
*A Demonstration of Interval Censoring in Large-Scale Databases*  

Advisor: Prof. Enrico Antônio Colosimo  
Co-Advisor: Prof. Jorge Gustavo Meléndez Velásquez  

View full thesis [here](https://drive.google.com/file/d/1GVN3FMvbrB2e_8OFP02o90Jyiq030eni/view?usp=drive_link)

---

### **Poster Presentation at 12th Brazilian Congress of Epidemiology**

**BMI AND HEIGHT ADJUSTMENTS IN SIX MILLION BRAZILIAN CHILDREN BY REGION**  

Advisor: Prof. Jorge Gustavo Meléndez Velásquez  

View full poster [here](https://drive.google.com/file/d/16fZf4IfT-dij0VjZnHzs8OfRFIIhCNbv/view?usp=sharing)

---

### **Oral Presentation at II International Conference on Public Policies and Data Science**  

**INFLUENCE OF INCOME TRANSFER POLICIES ON BRAZILIAN ELECTIONS**  
*A Comparative Analysis of Electoral Geography in 2014, 2018, and 2022 Presidential Elections*  

Authors: João Paulo Dellasta do Nascimento, Sofia M Aguiar  

---

### **Book Chapter in 'Impacts of the COVID-19 Pandemic on Education: Challenges, Adaptations, and the Future of Teaching Practice'**   

**INEQUALITY IN SECONDARY EDUCATION AND STUDENT PERFORMANCE IN THE ENEM EXAM**  

Authors: Aline Cristina Pinto; Maria Cecília Figueiredo Lopes; Renan Junio Gomes Machado; Sofia Moreira de Aguiar  

ISBN: 978-65-993373-5-2 | DOI: 10.5281/zenodo.4646433 

---

### **Presentation at National Congress on University, Distance Education, and Free Software 2020.1**  

**INEQUALITY IN SECONDARY EDUCATION AND STUDENT PERFORMANCE IN THE ENEM EXAM**  

Authors: Aline Cristina Pinto; Maria Cecília Figueiredo Lopes; Renan Junio Gomes Machado; Sofia Moreira de Aguiar  

