project:
  type: website

website:
  title: "Sof Aguiar"
  navbar:
    left:
      - href: content/index.qmd
        text: Home
      - content/about.qmd
      - content/publications.qmd
      - content/contact.qmd
      - content/blog.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: assets/styles.css
    toc: true



