project:
  type: website
  output-dir: docs 

website:
  title: "Sof Aguiar"
  favicon: assets/favicon.ico
  navbar:
    right:
      - text: "Português"
        href: ptbr/about.qmd
      - text: "English"
        href: en/about.qmd



format:
  html:
    theme:
      light: [assets/custom.scss]
    toc: false
