project:
  type: website
  output-dir: docs

website:
  title: "Sof Aguiar"
  description: "Personal website of Sof Aguiar [Sofia Moreira de Aguiar], showcasing portfolio, publications, and blog posts."
  favicon: assets/favicon.ico
  navbar:
    left:
      - href: content/index.qmd
        text: Home
      - href: content/about.qmd
        text: About
      - href: content/publications.qmd
        text: Publications
      - href: content/portfolio.qmd
        text: Portfolio
      - href: content/contact.qmd
        text: Contact Me
      - text: Blog
        menu:
          - text: Tech
            href: content/blog/tech.qmd
          - text: Life
            href: content/blog/life.qmd
    right:
      - icon: fab fa-github
        href: https://github.com/SofAguiar

format:
  html:
    css: 
      - assets/styles.css
    include-after-body: assets/scripts.js
    theme: 
      - light
      - dark