project:
  type: website

website:
  title: "Sof Aguiar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - contact.qmd
      - blog.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



