project:
  type: website
  output-dir: docs

website:
  title: "Sof Aguiar"
  navbar:
    left:
      - href: content/index.qmd
        text: Home
      - href: content/about.qmd
        text: About
      - href: content/publications.qmd
        text: Publications
      - href: content/portfolio.qmd
        text: Portfolio
      - href: content/contact.qmd
        text: Contact Me
      - text: Blog
        href: content/blog.qmd
    

format:
  html:
    css: assets/styles.css
