project:
  type: website
  output-dir: docs

website:
  title: "Sof Aguiar"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: home
      - href: about.qmd
        text: About
        icon: user
      - href: publications.qmd
        text: Publications
        icon: file-alt
      - href: portfolio.qmd
        text: Portfolio
      - href: contact.qmd
        text: Contact Me
      - text: Blog
        menu:
          - href: blog.qmd
            text: All Posts
          - href: blog-category-1.qmd
            text: Category 1
          - href: blog-category-2.qmd
            text: Category 2
  css:
    - styles.css