project:
  type: website
  output-dir: docs

website:
  title: "Sof Aguiar"
  navbar:
    left:
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Papers"
        href: papers.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Portfolio"
        href: portfolio.qmd
    right:
      - text: "en / pt-br"
        href: "#"  # Placeholder for language toggle

format:
  html:
    theme:
      light: [sandstone, custom.scss]
    toc: true
