# Prazer, Sofia Aguiar!
*Estatítica | Cientista de Dados | Pesquisadora em Saúde Pública*  

Eu sou graduanda em Estatística e apaixonada por Saúde Pública. O meu foco de pesquisa é aplicar métodos estatísticos e computacionais para dados epidemiológicos com o objetivo de entender doenças, prever casos e pensar estratégias para a saúde coletiva.

## Educação  
- **Graduação em Estatística** (UFMG, previsão de formatura em 2025/1)  

## Experiência Acadêmica
- **Iniciação Científica** sob orientação do professor Gustavo Velásquez no **Núcleo Interdisciplinar de Estudos e Pesquisa em Epidemiologia** da Escola de Enfermagem/UFMG (agosto/2023 - presente)
- **Iniciação Científica** sob orientação do professor Flávio Figueredo no **Uncertainty in Artificial Intelligence Lab** do Departamento de Ciências da Computação/UFMG (outubro/2021 - outubro/2022)
- **Diretora Presidente** na empresa júnior **ESTAT-MG** (janeiro - dezembro 2022)


## Fora do trabalho  
Além de estatística e computação, amo fazer arte e artesanato. Pinto, costuro, bordo e o que mais estiver ao alcance.


## Entre em contato e veja mais!  
- Email: sofia.aguiar42@gmail.com    
- Projetos de programação: [GitHub](https://github.com/SofAguiar)  
- Currículo acadêmico: [Lattes](http://lattes.cnpq.br/0041260570017557) 
- Perfil acadêmico internacional: [OrcID](https://orcid.org/0009-0007-8242-7487)

### Meus projetos favoritos

- [Análise de Sobrevivência Intervalar](blog/survival-analysis.qmd) - Uma aplicação dos métodos de análise de sobrevivência intervalar com banco de dados sintético.

- [Krigagem Ordinária em Python](blog/Interpolação_Clima.ipynb) - Um exercício para realizar krigagem de dados climáticos de Minas Gerais com Python


### Tutoriais em R para pesquisadores

- [Análise Exploratória](blog/data-viz.qmd) - Um breve passo a passo de como olhar para seu dataset

> **Aviso:** Este site está em desenvolvimento. Mudanças podem ocorrer!